// Dragons
export const NEST_UPDATEVAL = 'NEST/UPDATEVAL';
export const NEST_ADDDRAGON = 'NEST/ADDDRAGON';
export const NEST_DELDRAGON = 'NEST/DELDRAGON';
export const NEST_ADDERROR = 'NEST/ADDERROR';
export const NEST_UPDATECOUPLE = 'NEST/UPDATECOUPLE';

// Knights
export const BARRACK_UPDATENAME = 'BARRACK/UPDATENAME';
export const BARRACK_UPDATEAGE = 'BARRACK/UPDATEAGE';
export const BARRACK_ADDKNIGHT = 'BARRACK/ADDKNIGHT';
export const BARRACK_DELKNIGHT = 'BARRACK/DELKNIGHT';
export const BARRACK_ADDERROR = 'BARRACK/ADDERROR';
export const BARRACK_UPDATECOUPLE = 'BARRACK/UPDATECOUPLE';

// Couples
export const COUPLES_SETKNIGHT = 'COUPLES/SETKNIGHT';
export const COUPLES_SETDRAGON = 'COUPLES/SETDRAGON';
export const COUPLES_CREATE = 'COUPLES_CREATE';