// Dragons
export const NEST_UPDATEVAL = 'NEST/UPDATEVAL';
export const NEST_ADDDRAGON = 'NEST/ADDDRAGON';
export const NEST_DELDRAGON = 'NEST/DELDRAGON';
export const NEST_ADDERROR = 'NEST/ADDERROR';

// Knights
export const BARRACK_UPDATENAME = 'BARRACK/UPDATENAME';
export const BARRACK_UPDATEAGE = 'BARRACK/UPDATEAGE';
export const BARRACK_ADDKNIGHT = 'BARRACK/ADDKNIGHT';
export const BARRACK_ADDERROR = 'BARRACK/ADDERROR';